language: python
python:
- 3.6.5
services:
- postgresql
env:
- DB=postgres DATABASE_URL='postgresql://postgres@localhost:5432/alissproject' DJANGO_VERSION=1.11.8
  DJANGO_SETTINGS_MODULE='config.settings.local' SECRET_KEY='thisisasecrettkey' ALLOWED_HOSTS='localhost,www.localhost'
  ELASTICSEARCH_URL=http://localhost:9200 ELASTICSEARCH_USERNAME='' ELASTICSEARCH_PASSWORD=''
  CLOUDINARY_CLOUD_NAME='test' CLOUDINARY_API_KEY='test' CLOUDINARY_API_SECRET='test'
  CLOUDINARY_URL='cloudinary://x:y@z'
before_install:
- curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.5.4.deb
  && sudo dpkg -i --force-confnew elasticsearch-6.5.4.deb && sudo service elasticsearch
  restart
install:
- pip install -r requirements.txt
before_script:
- sleep 10
script:
- python manage.py shell --command="from aliss.search_tasks import create_index; create_index()"
- python manage.py collectstatic
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: BWMfE40cTZobWVdBZw6NQNqc8OMPCXsepn0KDfg7cVMUUHcWhUkY3QAjizLbVZ6hhaNRlz/SaBDlZjlWpX+IlYONVR5odVl04q+gvLzLlWUzB5KPeD6ISPCDqH80cORS42tEhyv+eB4+Th80dPcBc4Ls0HlCDRmIvZCzudvVBJwTxVWyEJRMWMU47xvztFnFHXCJSrGsQwNR7qT0bnAZ2htfdE60gtH5iniWu717kvTgs1NI/nOkSnv3Y9YX2+9/ylLACpg1JaRTmNlP7kofrnBDrxzdvTEi14PkvaeCFMrSUO9hx7kdbAXy0DGsRCrSWz6+Eojq8WGEPxBGD4+FapWmGPBLqtE+r2RlrN3ZgyGPj/hK4cjMTpISIiyoWTqRHmm3hRQ00CuMfqcZ6kVJqirdTBZ+qpiYGI7TbTZQF89l0NrIaL7yIHuRqCFwCWmTTH+9edjR1Md2hxVUrs5Q1hiJD8nbSFHVZOMwSitprmng0BZAK0sWGGk8yHHsAWt9sUfO/5pOZz7mPb1pJhS1AO0FXBqivBqxbotmOQT4ogrEqjV8GL5LsY0SmEWpCJvtFpgiyEMZDM1ISrkhGykGp51UbpZENJV39pfxpQJwjYSXAz/EyUnwTBtWbPLQHPvzAM0ZKl2qDOm9oj3+O+kXdZefami/AiYAQPRpblsXQ3U=
  app: staging-aliss
  on:
    repo: staging
notifications:
  slack:
    rooms:
      - aliss-team:myOYfFm3gWKEUPcVvRszq6uQ#dev
    on_success: always
    secure: r42Kyq1vCFG3NKaROnrkz3IEry7LA+1QGkLORHlwB7kJhZqtFOJ2ggMZzAsi9k0bEB2l+v+0PIuecNiARwINVZp2dlce0y482rLcQ7QjXkN/g8CjgsceMm4dseHxg6tj09Y/s46uxIdgvxELa14C0cY5xMew7MPFgctKrj3AhQw0qTBd3VffOlXsqvP26osx8u+g6Y28sAt1401vVOQFCYgFxut8hBVuesq8gWpo5K5i1bmMDNs1kZs3h28sVzvgjr7gxdBFVtREiIpWTTVJFJlK2ghNooYXHyy69q0+7JKY447CV/Ixyqp7xhGw9vcXKSsJjQdF1X7ZqWdhDYx1BKkWSiEye9PG/x8Ut/Uh1l9+xmh64aoeMrqqRwZocPx/mXPFyY9hxWM9PtBGP/bT1f9d+TtZ1nbp1AKOmbQpGZRnlCHt3Ll7f5UJwHrRJfau2RyR7M9JqYXv0AiFWT+86VYoKoEPJBSJAynAIIhjZVXVRdrX1hFVyBRm20vEK9ZR6EVowyvEzoAk1XQM4iEdrN4UV6QCBGUS9ptEmE48Cfgsg1ukFapB6cOigd01YhT2vvHnwIUV/rWn1BwIVAQVfJ0v3Cn9mI0exhMOjlNfdz76Q+P8F2HIul0Iob2UoRyWMMIlRj0HZ4Ir08OzW7h6hW0V7D4K3bQ4KMmcZ6w72dg=
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit}): %{message}"
  email: false