language: python
python:
  - "3.6.5"
services:
  - postgres
  - elasticsearch
env:
  - DB=postgres DATABASE_URL='postgresql://postgres@127.0.0.1:5432/alissproject' DJANGO_VERSION=1.11.8 DJANGO_SETTINGS_MODULE='config.settings.local' SECRET_KEY='thisisasecrettkey' ALLOWED_HOSTS='localhost,www.localhost' ELASTICSEARCH_URL=http://localhost:9200 ELASTICSEARCH_USERNAME='' ELASTICSEARCH_PASSWORD=''
install:
  - pip install -r requirements.txt
before_script:
  - sleep 10
script:
  - python manage.py shell --command="from aliss.search import create_index; create_index()"
  - python manage.py collectstatic
  - python manage.py test
